= How to add service

Services will be added on this page if the following service_documentation modile is added to the application repo and it is part of the nsbno org.

Only applications should be added
- no adapters
- no user surfaces

For any questions please contact us on the slack channel #team-infrastruktur-public

== Guide

Code snippet to be added

[.terraform]
....
module "service_documentation" {
  source                      = "github.com/nsbno/servicedocumentation//modules/plain-servicedoc"
  application_name            = "${local.name_prefix}-${local.application_name}"  
  env                         = local.environment
  current_account_id          = data.aws_caller_identity.this.account_id
  slack                       = "#team-kanalname"
  owner                       = "budgetowner@vy.no"
  technicalowner              = "tekniskowner@vy.no"
  servicesla                  = "99.7"
  growthmetric                = "transaction count"
  aktivitetskode              = "123456"
}
....

CircleCI config for generating swagger file
[.yml]
....
orbs:
documentation: "vydev/service-documentation@0.0.1"

parameters:
      - documentation/publish-openapi-spec:
          path: backend/target/openapi/openapi.json
          context: digitalekanaler
          filters:
            branches:
              only: master
....



Example for projects with api documentation in api gateway:
[.terraform]
....
module "service_documentation" {
  source                      = "github.com/nsbno/servicedocumentation//modules/api-gateway"  
  name_prefix                 = local.name_prefix
  env                         = local.environment
  current_account_id          = data.aws_caller_identity.this.account_id
  slack                       = "#team-kanalname"
  owner                       = "budgetowner@vy.no"
  technicalowner              = "tekniskowner@vy.no"
  servicesla                  = "99.7"
  growthmetric                = "transaction count"
  aktivitetskode              = "123456"
  api_gateway_id              = module.api_gateway.rest_api_id
}
....



